'use strict';

// Central registry of all module question data for the dashboard drill-down.
// Add new modules here as the programme grows — no other file needs changing.
const DASH_MODULE_REGISTRY = {
  mod1: {
    label: 'MOD 1 — Baseline & Workflow',
    totalQ: 16,
    answerKey: {
      Q1:'A', Q2:'B', Q3:'C', Q4:'A',  Q5:'C',  Q6:'A',  Q7:'D',  Q8:'C',
      Q9:'D', Q10:'B', Q11:'B', Q12:'C', Q13:'D', Q14:'B', Q15:'D', Q16:'A'
    },
    questions: [
      { id:1,  text:'Why is Hasbro implementing the new Forecast Enrichment process now?', options:{ A:'To address chronic gaps in forecast traceability, manual workload, and the ability to measure the value of commercial intelligence.', B:'To replace Logility with Daybreak as the planning system.', C:'To reduce the number of Demand Planning resources required each cycle.', D:'To consolidate Sales, Marketing, and Demand Planning under a single team.' }, slideRefs:'2, 4', section:'Why we\'re changing' },
      { id:2,  text:'Which statement best describes the role of the Daybreak statistical baseline in the new process?', options:{ A:'Daybreak produces the final forecast used directly by Supply Planning; no further input is needed.', B:'Daybreak models baseline demand behavior; commercial input must be added through enrichments to capture what the historical data cannot see.', C:'Sales, Marketing, and Demand Planning each maintain independent baselines that are reconciled at year-end.', D:'The baseline replaces all commercial input; enrichments are optional refinements.' }, slideRefs:'4, 5', section:'End-to-end picture' },
      { id:3,  text:'Which statement is correct about the Daybreak statistical baseline?', options:{ A:'It is built by Sales each cycle based on customer commitments.', B:'It is set to the prior year\'s volume adjusted by a fixed growth factor.', C:'It uses Hasbro\'s real historical shipment data and item attributes — through machine learning — to predict future demand patterns.', D:'It is identical to the Financial Forecast and updated on the same cadence.' }, slideRefs:'8, 10', section:'Statistical Baseline 101' },
      { id:4,  text:'Which statement correctly describes the three-party operating model that produces the baseline?', options:{ A:'Daybreak provides the machine-learning engine; Genpact executes the operational tasks; Hasbro Demand Planning owns governance and sign-off.', B:'Genpact provides the engine; Daybreak validates the outputs; Hasbro Demand Planning sets the parameters.', C:'Hasbro Demand Planning generates the baseline; Genpact provides the model design; Daybreak hosts the data.', D:'All three parties contribute equally to model generation, validation, and sign-off.' }, slideRefs:'11', section:'Statistical Baseline 101' },
      { id:5,  text:'Which SKUs are treated using Daybreak\'s standard machine-learning forecasting approach?', options:{ A:'All active SKUs in the portfolio, including new product introductions.', B:'Pure NPI items in their first 12 months of life.', C:'Carry-Forward items with at least 52 weeks of historical shipment data.', D:'Fan items, regardless of how much history they have.' }, slideRefs:'12, 13', section:'SKU Types' },
      { id:6,  text:'How is an NPI\'s forecast generated during its cold-start phase (0–8 weeks of history)?', options:{ A:'By shaping the Brand Plan annual volume with attribute-based shape and level models (category, launch timing, price tier).', B:'By copying the predecessor product\'s historical pattern.', C:'By projecting the first month of actuals forward.', D:'By applying Daybreak\'s carry-forward model with extrapolated history.' }, slideRefs:'14', section:'SKU Types' },
      { id:7,  text:'Why are UK Fan items handled without a statistical baseline?', options:{ A:'Daybreak\'s licensing model prevents its use on Fan products.', B:'Fan volume is too small to justify the model\'s processing cost.', C:'Fan items are forecasted in a separate system maintained by Marketing.', D:'Fan demand is driven by entertainment events with no recurring pattern; historical data cannot meaningfully predict future demand. Marketing and Commercial build the forecast directly.' }, slideRefs:'15', section:'SKU Types' },
      { id:8,  text:'At which planning level is the Daybreak statistical baseline generated?', options:{ A:'Planning Level 1 — Customer × Planning SKU × Channel.', B:'Planning Level 2 — Planning SKU × Customer.', C:'Planning Level 3 — Parent SKU × Business Unit × Channel.', D:'Planning Level 5 — Brand × Business Unit.' }, slideRefs:'10, 16', section:'Disaggregation' },
      { id:9,  text:'What is the purpose of forecast disaggregation in the new process?', options:{ A:'To convert weekly forecasts into monthly buckets for financial reporting.', B:'To translate the Consensus Forecast into the Financial Forecast for the budget cycle.', C:'To split the forecast between Domestic and Direct Import channels.', D:'To break the L3 statistical baseline down to the Customer × Planning SKU × Channel level (L1), so that Sales can review and enrich the forecast at the level where commercial decisions are made.' }, slideRefs:'16', section:'Disaggregation' },
      { id:10, text:'How does the disaggregation method differ between a Carry-Forward item and an NPI item?', options:{ A:'Both methods are identical — only the source system differs.', B:'Carry-Forward uses the SKU\'s own statistical proportionality based on its history; NPI uses brand-level historical customer mix combined with P2M volume splits, because the NPI has no shipment history of its own.', C:'Carry-Forward is disaggregated manually; NPI is disaggregated automatically.', D:'Carry-Forward is disaggregated only at L1; NPI only at L3.' }, slideRefs:'17, 19, 20, 21', section:'Disaggregation' },
      { id:11, text:'What is the purpose of the Forecasting Range?', options:{ A:'It controls when Daybreak runs the statistical model for each cycle.', B:'It defines, per customer × SKU, the period during which the customer should receive baseline disaggregation. Outside that period, the customer is excluded from the disaggregation logic.', C:'It sets the look-back window used by the Logility Moving Average Model.', D:'It determines the timing of the Joint Marketing & Demand Planning Reconciliation Session.' }, slideRefs:'22', section:'Disaggregation' },
      { id:12, text:'Which statement best describes when an enrichment should be applied to the baseline?', options:{ A:'On every SKU in the portfolio, each cycle, to confirm review.', B:'Only when Marketing or Demand Planning requests an adjustment.', C:'Only for events the statistical baseline cannot see — known commercial activity, structural changes, supply-related shifts, or committed plans.', D:'Only when the forecast is below the Financial Forecast target.' }, slideRefs:'25', section:'Enrichment Principles' },
      { id:13, text:'What is the purpose of the Joint Marketing & Demand Planning Reconciliation Session?', options:{ A:'To allow Marketing to override Sales\' L1 enrichments in cases where Marketing has better visibility.', B:'To finalize the Daybreak baseline before it is loaded to Logility for the cycle.', C:'To replace the legacy Brand DMR meetings that exist today in North America.', D:'To combine the bottom-up commercial view with top-down statistical and brand-strategic views, apply BU-level corrections, and prepare the proposal for Executive Sign-Off.' }, slideRefs:'32', section:'Reconciliation' },
      { id:14, text:'In the UK pilot, which statement correctly describes the scope split between Key Account Managers (KAMs) and Brand Captains?', options:{ A:'Both roles can edit the baseline at any planning level; the most recent edit wins.', B:'Brand Captains own SKU × BU-level (Level 2.5) Base Trend adjustments. KAMs capture account-specific enrichments and account-level deltas at L1; baseline adjustments by KAMs are exceptions, not the default.', C:'Only Demand Planning can adjust the baseline; both KAMs and Brand Captains submit requests for review.', D:'The KAM owns baseline adjustments at all levels; the Brand Captain reviews after the fact.' }, slideRefs:'33', section:'UK Pilot Roles' },
      { id:15, text:'In the 2026 UK pilot, how does HERO present the starting forecast to Brand Captains at the beginning of each cycle?', options:{ A:'Empty — Brand Captains build the forecast from scratch each cycle.', B:'Pre-populated with the prior month\'s consensus forecast.', C:'Pre-populated with the Daybreak baseline only; Captains rebuild everything else manually.', D:'Pre-populated with the deltas between the Daybreak baseline and the current resultant forecast. Captains capture only the changes they intend to move the resultant — no manual matching is required.' }, slideRefs:'33', section:'End-to-end Workflow' },
      { id:16, text:'In the 2027 target operating model, how does the Brand Captain\'s role differ from the 2026 pilot?', options:{ A:'Brand Captains start from the Daybreak baseline directly. Corrections for commercial or supply events affecting the forecast are captured as Base Trend adjustments.', B:'Brand Captains are removed; cycles run fully automated.', C:'Brand Captains operate exclusively at Level 1 (customer level), with KAMs handling BU-level decisions.', D:'Brand Captains review a pre-populated forecast and confirm without modification.' }, slideRefs:'33', section:'End-to-end Workflow' }
    ]
  },
  mod2: {
    label: 'MOD 2 — Enrichment Practice',
    totalQ: 15,
    answerKey: {
      Q1:'A', Q2:'B', Q3:'C', Q4:'C', Q5:'D',
      Q6:'B', Q7:'B', Q8:'C', Q9:'A', Q10:'A',
      Q11:'D', Q12:'C', Q13:'A', Q14:'D', Q15:'B'
    },
    questions: [
      { id:1,  text:'A carry-forward item shows two consecutive years of stable seasonal demand, with no confirmed commercial event, no supply issue, and no distribution change in scope. The Daybreak baseline and the Resultant Forecast track the same seasonal shape at L3. What is the correct action?', options:{ A:'Accept the L3 baseline — no enrichment required.', B:'Apply a positive base trend adjustment to lock the seasonal pattern into next year.', C:'Override the Daybreak baseline with the Sales Forecast.', D:'Submit a disaggregation adjustment request to DP/Genpact.' }, slideRefs:'4, 5, 6', section:'Baseline Training' },
      { id:2,  text:'You are reviewing a scenario where the total demand at L3 looks correct against history, but the customer-level split at L2 routes most of the volume to inactive partners. Where does the issue live?', options:{ A:'In the L3 baseline — apply a base trend correction.', B:'In the L2 disaggregation logic — the split method needs to be changed.', C:'In the L1 enrichments — remove the enrichments for inactive customers.', D:'In the L2 disaggregation logic — switch the method from Moving Average to Current Resultant.' }, slideRefs:'4', section:'Baseline Training' },
      { id:3,  text:'An item shipped near zero for several months in 2025 because of a confirmed stockout. The Daybreak baseline now projects 2026 demand at a fraction of the pre-stockout run-rate, because the model learned the suppression as true decline. What is the correct action?', options:{ A:'Apply a positive promo enrichment to lift demand back to historical levels.', B:'Override the Daybreak baseline with the Sales Forecast each cycle going forward.', C:'Cleanse the stockout-affected months in historical data so Daybreak can rebuild an accurate baseline.', D:'Accept the Daybreak baseline — the model is reading the most recent year correctly.' }, slideRefs:'7, 8', section:'Baseline Training' },
      { id:4,  text:'A Warm Start NPI with under 12 months of history has 16 weeks of actuals below the 2026 Resultant plan, and Daybreak has slashed the 2027 baseline by more than half. After reviewing together, you and the Brand Captain agree Daybreak\'s drop is too aggressive and the SKU can still rebound. What is the correct action?', options:{ A:'Accept the Daybreak 2027 baseline — 16 weeks of actuals is sufficient to confirm the structural decline.', B:'Apply negative sets in each under-performing month to align the forecast to Daybreak\'s corrected view.', C:'Recalculate overall demand and apply an L2.5 Base Trend adjustment via the Brand Captain\'s reconciliation template.', D:'Submit a disaggregation request to DP/Genpact to redistribute the volume across a wider customer base.' }, slideRefs:'9, 10', section:'Baseline Training' },
      { id:5,  text:'A carry-forward item is exclusive to a single retailer — that retailer absorbs ~100% of actuals across the past two years. The Current Resultant disaggregation routes a large share to other customers with no recent history, while the Moving Average method routes ~100% to the exclusive partner. What is the correct action?', options:{ A:'Keep the Current disaggregation; the model will self-correct over time.', B:'Apply a negative base trend to remove the non-active customers.', C:'Submit a disaggregation request to DP/Genpact to rebuild the customer hierarchy.', D:'Switch the L2 disaggregation method from Current to Moving Average.' }, slideRefs:'11, 12, 13, 14', section:'Baseline Training' },
      { id:6,  text:'Which statement correctly describes the difference between a Set and a Base Trend enrichment?', options:{ A:'A Set is positive only; a Base Trend can be positive or negative.', B:'A set cleanses out of the historical shipments after the period passes; base trend adjustment are never used to clean the history therefore its impact remains.', C:'A Set is owned by Sales; a Base Trend is owned by Demand Planning.', D:'A Set applies to NPI items only; a Base Trend applies to carry-forward items only.' }, slideRefs:'24', section:'Set vs Base Trend' },
      { id:7,  text:'A customer pulls confirmed annual demand into a specific order window (ladder), with offsetting reductions in the months from which demand is being moved. The full-year total does not change. Which enrichment approach is correct?', options:{ A:'Positive base trend in the ladder month + negative base trend in the pulled-from months.', B:'Positive set in the ladder month + negative sets in the pulled-from months.', C:'Single positive base trend in the ladder month — the negative offset is not needed.', D:'No enrichment — let the baseline absorb the timing shift over the next cycle.' }, slideRefs:'32', section:'Set vs Base Trend' },
      { id:8,  text:'A customer is adding new stores to its distribution. The initial pipeline fill ships in one window (F1), and ongoing replenishment continues in those new stores afterwards. Which enrichment approach is correct?', options:{ A:'Single base trend from F1 onward — covers both the fill and ongoing replenishment.', B:'Single set in F1 — covers the fill; the model will pick up the new run-rate from actuals.', C:'Set in F1 for the new-store fill + base trend from F2 onward for ongoing replenishment.', D:'Two sets — one in F1 for the fill, one in F2 onward for replenishment.' }, slideRefs:'29', section:'Set vs Base Trend' },
      { id:9,  text:'An established carry-forward item has a future confirmed retail promotion that is not already reflected in baseline behavior. The promo will generate incremental units in a specific ship window. Which enrichment is correct?', options:{ A:'Promo enrichment for the confirmed incremental units in the relevant ship week(s).', B:'Positive base trend for the promo lift, to persist into future cycles.', C:'Set enrichment for the entire month containing the promo.', D:'No enrichment — the baseline will capture the lift once actuals come in.' }, slideRefs:'26', section:'Enrichment Types' },
      { id:10, text:'A customer has provided a specific pre-order quantity and timing for a new item with no comparable history. What is the correct way to capture it?', options:{ A:'Pre-order enrichment for the confirmed quantity and timing only.', B:'Pre-order enrichment for the confirmed quantity, plus an additional run-rate estimate for the rest of the year.', C:'Set enrichment for the pre-order, then convert to base trend once actuals start coming in.', D:'No enrichment — the NPI baseline will absorb the pre-order.' }, slideRefs:'37', section:'Enrichment Types' },
      { id:11, text:'An NPI\'s stat baseline already includes the channel-fill volume in its launch shape, but the team needs the fill visible as a discrete set for allocation traceability. What is the correct approach in F1?', options:{ A:'Add a positive set for the channel-fill on top of the existing baseline.', B:'Apply a positive base trend in F1 to make the channel-fill visible.', C:'Submit a disaggregation request to split the channel-fill into a separate baseline component.', D:'To reflect a negative base trend enrichment in correspondent period to offset the channel-fill already inside the baseline, plus a positive set enrichment of equal magnitude in the same month.' }, slideRefs:'31', section:'Enrichment Types' },
      { id:12, text:'Last year a deal spike inflated demand for a specific period, and the promotion is not repeating this year. The baseline is now projecting the spike forward as if it were normal seasonality. What is the correct action?', options:{ A:'Apply a positive promo enrichment to confirm the new run-rate.', B:'Submit a disaggregation adjustment to redistribute the spike across customers.', C:'Apply a negative base trend to remove the phantom spike from the projection.', D:'Let the baseline run — actuals will pull it back to normal within two cycles.' }, slideRefs:'39', section:'Base Trend Corrections' },
      { id:13, text:'A specific customer has discontinued an item that remains active at other customers. The baseline is still allocating volume to the dropped customer based on past proportions. What is the correct action?', options:{ A:'Apply a negative base trend and update the forecasting range to stop allocating to that customer.', B:'Wait — the model will reduce the customer\'s share once actuals show zero.', C:'Submit a disaggregation request to remove the customer from the L2 split.', D:'Apply a one-time negative set for the year, then let the baseline rebuild.' }, slideRefs:'44', section:'Base Trend Corrections' },
      { id:14, text:'A customer is changing its buying route from Domestic to Direct Import. Total demand is unchanged — only the channel is moving. The volume in scope currently sits in the baseline. What is the correct approach?', options:{ A:'Create a positive enrichment on DI and an offsetting negative enrichment on DOM.', B:'Submit a disaggregation request to reroute the volume between channels.', C:'Apply a base trend on DI to grow the channel; let DOM decay through actuals.', D:'Use the channel-shift functionality on the baseline to move volume from DOM to DI.' }, slideRefs:'51', section:'No-Enrichment Paths' },
      { id:15, text:'At the BU/brand level the L3 total is accurate against history, but the L2 customer split allocates too much volume to a customer with declining actuals. What is the correct path?', options:{ A:'Apply a negative enrichment on the over-allocated customer to bring the split back in line.', B:'Submit a disaggregation adjustment request to DP/Genpact to rebuild the customer proportions.', C:'Apply a base trend at L3 to grow overall volume and compensate for the misallocation.', D:'No enrichment — let actuals pull the split back over time.' }, slideRefs:'54', section:'No-Enrichment Paths' }
    ]
  }
};
