// GENERATED by tools/generate_registry.js from KC_Canonical_QuestionBank_v8_2026-09-01.json — do not edit by hand.
// Single source for the module set. Re-run the generator after changing the bank.
'use strict';
window.HERO_MODULES = [
  { id: 'mod1', num: 1, label: 'MOD 1 — Baseline & Workflow', short: 'MOD 1', track: 'main', group: 'Main programme', url: 'index.html', total: 16, pass: 13 },
  { id: 'mod2', num: 2, label: 'MOD 2 — Enrichment Practice', short: 'MOD 2', track: 'main', group: 'Main programme', url: 'mod2.html', total: 15, pass: 12 },
  { id: 'mod3', num: 3, label: 'MOD 3 — HERO in Practice', short: 'MOD 3', track: 'main', group: 'Main programme', url: 'mod3.html', total: 10, pass: 8 },
  { id: 'mod4', num: 4, label: 'MOD 4 — Exceptions & Customer Variations', short: 'MOD 4', track: 'main', group: 'Main programme', url: 'mod4.html', total: 10, pass: 8 },
  { id: 'mod5', num: 5, label: 'MOD 5 — Reconciliation & Decision Narrative', short: 'MOD 5', track: 'main', group: 'Main programme', url: 'mod5.html', total: 15, pass: 12 },
  { id: 'mod7', num: 7, label: 'MOD 7 — HERO Data Flow & Cycle Start', short: 'MOD 7', track: 'main', group: 'Main programme', url: 'mod7.html', total: 10, pass: 8 },
  { id: 'speed1', num: 101, label: 'SESSION 1 — Introduction to the Enrichment Process', short: 'SPEED 1', track: 'speed', group: 'Speed Training', url: 'speed1.html', total: 10, pass: 8 },
  { id: 'speed2', num: 102, label: 'SESSION 2 — Where the Number Comes From', short: 'SPEED 2', track: 'speed', group: 'Speed Training', url: 'speed2.html', total: 10, pass: 8 },
  { id: 'speed3', num: 103, label: 'SESSION 3 — The Tool, End to End', short: 'SPEED 3', track: 'speed', group: 'Speed Training', url: 'speed3.html', total: 10, pass: 8 },
  { id: 'speed4', num: 104, label: 'SESSION 4 — How Your Market Works', short: 'SPEED 4', track: 'speed', group: 'Speed Training', url: 'speed4.html', total: 10, pass: 8 }
];

(function () {
  function esc(s){return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');}
  function current(){ return (document.body && document.body.dataset) ? document.body.dataset.module : null; }
  function option(m, cur){
    return '<option value="'+m.id+'"'+(m.id===cur?' selected':'')+'>'+esc(m.label)+'</option>';
  }
  // Grouped by track, so the two programmes never read as one numbered list.
  // A single-track registry renders flat, exactly as before.
  function fillSelect(){
    var sel = document.getElementById('module-select'); if(!sel) return;
    var cur = current();
    var groups = [];
    window.HERO_MODULES.forEach(function(m){
      var name = m.group || '';
      var g = groups.filter(function(x){ return x.name === name; })[0];
      if(!g){ g = { name: name, items: [] }; groups.push(g); }
      g.items.push(m);
    });
    var body = groups.length < 2
      ? window.HERO_MODULES.map(function(m){ return option(m, cur); }).join('')
      : groups.map(function(g){
          return '<optgroup label="'+esc(g.name)+'">' +
            g.items.map(function(m){ return option(m, cur); }).join('') + '</optgroup>';
        }).join('');
    sel.innerHTML = '<option value="">— Choose a module —</option>' + body;
  }
  function fillFilters(){
    var host = document.getElementById('dash-mod-filters'); if(!host) return;
    host.innerHTML = window.HERO_MODULES.map(function(m){
      return '<label style="display:flex;align-items:center;gap:6px;font-size:13px;color:var(--gray-light);cursor:pointer;">' +
        '<input type="checkbox" class="mod-filter-check" value="'+m.id+'" checked style="accent-color:var(--teal);width:14px;height:14px;cursor:pointer;"> ' +
        esc(m.label) + '</label>';
    }).join('');
  }
  document.addEventListener('DOMContentLoaded', function(){ fillSelect(); fillFilters(); });
})();
