// GENERATED by tools/generate_registry.js from KC_Canonical_QuestionBank_v6_2026-08-17.json — do not edit by hand.
// Single source for the module set. Re-run the generator after changing the bank.
'use strict';
window.HERO_MODULES = [
  { id: 'mod1', num: 1, label: 'MOD 1 — Baseline & Workflow', short: 'MOD 1', url: 'index.html', total: 16, pass: 13 },
  { id: 'mod2', num: 2, label: 'MOD 2 — Enrichment Practice', short: 'MOD 2', url: 'mod2.html', total: 15, pass: 12 },
  { id: 'mod3', num: 3, label: 'MOD 3 — HERO in Practice', short: 'MOD 3', url: 'mod3.html', total: 10, pass: 8 },
  { id: 'mod4', num: 4, label: 'MOD 4 — Exceptions & Customer Variations', short: 'MOD 4', url: 'mod4.html', total: 10, pass: 8 },
  { id: 'mod5', num: 5, label: 'MOD 5 — Reconciliation & Decision Narrative', short: 'MOD 5', url: 'mod5.html', total: 15, pass: 12 },
  { id: 'mod7', num: 7, label: 'MOD 7 — HERO Data Flow & Cycle Start', short: 'MOD 7', url: 'mod7.html', total: 10, pass: 8 }
];

(function () {
  function esc(s){return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');}
  function current(){ return (document.body && document.body.dataset) ? document.body.dataset.module : null; }
  function fillSelect(){
    var sel = document.getElementById('module-select'); if(!sel) return;
    var cur = current();
    sel.innerHTML = '<option value="">— Choose a module —</option>' +
      window.HERO_MODULES.map(function(m){
        return '<option value="'+m.id+'"'+(m.id===cur?' selected':'')+'>'+esc(m.label)+'</option>';
      }).join('');
  }
  function fillFilters(){
    var host = document.getElementById('dash-mod-filters'); if(!host) return;
    host.innerHTML = window.HERO_MODULES.map(function(m){
      return '<label style="display:flex;align-items:center;gap:6px;font-size:13px;color:var(--gray-light);cursor:pointer;">' +
        '<input type="checkbox" class="mod-filter-check" value="'+m.id+'" checked style="accent-color:var(--teal);width:14px;height:14px;cursor:pointer;"> ' +
        esc(m.label) + '</label>';
    }).join('');
  }
  document.addEventListener('DOMContentLoaded', function(){ fillSelect(); fillFilters(); });
})();
