#!/usr/bin/env node
'use strict';
/*
 * generate_registry.js — SINGLE SOURCE OF MODULES.
 *
 * Reads the newest canonical bank and writes two generated files:
 *   - modules.js       : window.HERO_MODULES (id, num, label, short, url, total, pass)
 *                        plus self-init wiring that fills the nav <select id="module-select">
 *                        and the dashboard filter host <div id="dash-mod-filters"> on every page.
 *   - dashboard-data.js: DASH_MODULE_REGISTRY (label, totalQ, answerKey, questions) for drill-down.
 *
 * Adding a module to the bank and re-running this is enough for it to appear in the nav
 * menu and the dashboard filters everywhere. verify_registry.js fails the build if these
 * generated files or the pages drift from the bank.
 *
 * Sections (shown in drill-down) are harvested from each page's QUESTIONS array, since the
 * bank does not carry a section field.
 *
 * Usage: node tools/generate_registry.js
 */
const fs = require('fs');
const path = require('path');

const REPO = path.resolve(__dirname, '..');
const LET = ['A', 'B', 'C', 'D'];

function newestBank() {
  const banks = fs.readdirSync(REPO).filter(f => /^KC_Canonical_QuestionBank_v\d+.*\.json$/.test(f));
  banks.sort((a, b) => (parseInt((a.match(/_v(\d+)/) || [])[1] || 0)) - (parseInt((b.match(/_v(\d+)/) || [])[1] || 0)));
  return banks[banks.length - 1];
}
function pageFile(id) { return id === 'mod1' ? 'quiz.js' : `${id}.js`; }
function urlFor(quizUrl) {
  if (!quizUrl) return null;
  if (quizUrl.endsWith('/')) return 'index.html';
  return quizUrl.split('/').pop();
}
function esc(s) { return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;'); }
function jsstr(s) { return String(s).replace(/\\/g, '\\\\').replace(/'/g, "\\'"); }

// extract id->section from a page's QUESTIONS array
function extractSections(file) {
  const src = fs.readFileSync(path.join(REPO, file), 'utf8');
  const s = src.indexOf('const QUESTIONS'); const o = src.indexOf('[', s);
  let d = 0, i = o, inStr = false, sc = '', escc = false, end = -1;
  for (; i < src.length; i++) { const c = src[i];
    if (inStr) { if (escc) escc = false; else if (c === '\\') escc = true; else if (c === sc) inStr = false; continue; }
    if (c === "'" || c === '"' || c === '`') { inStr = true; sc = c; continue; }
    if (c === '[') d++; else if (c === ']') { d--; if (d === 0) { end = i; break; } } }
  const Q = eval(src.slice(o, end + 1)); // eslint-disable-line no-eval
  const map = {};
  for (const q of Q) map[q.id] = q.section || '';
  return map;
}

const bankFile = newestBank();
const bank = JSON.parse(fs.readFileSync(path.join(REPO, bankFile), 'utf8'));
const modules = bank.modules.slice().sort((a, b) =>
  parseInt(a.module_id.replace('mod', ''), 10) - parseInt(b.module_id.replace('mod', ''), 10));

// ---- modules.js ----
const reg = modules.map(m => {
  const num = parseInt(m.module_id.replace('mod', ''), 10);
  return {
    id: m.module_id, num, label: m.nav_label || m.title, short: 'MOD ' + num,
    url: urlFor(m.quiz_url), total: m.total_questions, pass: m.pass_threshold
  };
});
const modulesJs = `// GENERATED by tools/generate_registry.js from ${bankFile} — do not edit by hand.
// Single source for the module set. Re-run the generator after changing the bank.
'use strict';
window.HERO_MODULES = [
${reg.map(r => `  { id: '${r.id}', num: ${r.num}, label: '${jsstr(r.label)}', short: '${r.short}', url: '${r.url}', total: ${r.total}, pass: ${r.pass} }`).join(',\n')}
];

(function () {
  function esc(s){return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');}
  function current(){ return (document.body && document.body.dataset) ? document.body.dataset.module : null; }
  function fillSelect(){
    var sel = document.getElementById('module-select'); if(!sel) return;
    var cur = current();
    sel.innerHTML = '<option value="">— Choose a module —</option>' +
      window.HERO_MODULES.map(function(m){
        return '<option value="'+m.id+'"'+(m.id===cur?' selected':'')+'>'+esc(m.label)+'</option>';
      }).join('');
  }
  function fillFilters(){
    var host = document.getElementById('dash-mod-filters'); if(!host) return;
    host.innerHTML = window.HERO_MODULES.map(function(m){
      return '<label style="display:flex;align-items:center;gap:6px;font-size:13px;color:var(--gray-light);cursor:pointer;">' +
        '<input type="checkbox" class="mod-filter-check" value="'+m.id+'" checked style="accent-color:var(--teal);width:14px;height:14px;cursor:pointer;"> ' +
        esc(m.label) + '</label>';
    }).join('');
  }
  document.addEventListener('DOMContentLoaded', function(){ fillSelect(); fillFilters(); });
})();
`;
fs.writeFileSync(path.join(REPO, 'modules.js'), modulesJs);

// ---- dashboard-data.js ----
const parts = [];
parts.push("'use strict';");
parts.push('');
parts.push('// GENERATED by tools/generate_registry.js from ' + bankFile + ' — do not edit by hand.');
parts.push('// Central registry of all module question data for the dashboard drill-down.');
parts.push('const DASH_MODULE_REGISTRY = {');
modules.forEach((m, mi) => {
  const sections = fs.existsSync(path.join(REPO, pageFile(m.module_id))) ? extractSections(pageFile(m.module_id)) : {};
  const ak = m.questions.map(q => `${q.id}:'${q.correct}'`).join(', ');
  parts.push(`  ${m.module_id}: {`);
  parts.push(`    label: '${jsstr(m.nav_label || m.title)}',`);
  parts.push(`    totalQ: ${m.total_questions},`);
  parts.push(`    answerKey: { ${ak} },`);
  parts.push('    questions: [');
  m.questions.forEach(q => {
    const num = parseInt(q.id.replace('Q', ''), 10);
    const opts = LET.map(k => `${k}:'${jsstr(q.options[k])}'`).join(', ');
    const section = sections[num] || '';
    parts.push(`      { id:${num}, text:'${jsstr(q.text)}', options:{ ${opts} }, slideRefs:'${jsstr(q.slide_refs || '')}', section:'${jsstr(section)}' },`);
  });
  parts.push('    ]');
  parts.push('  }' + (mi < modules.length - 1 ? ',' : ''));
});
parts.push('};');
parts.push('');
fs.writeFileSync(path.join(REPO, 'dashboard-data.js'), parts.join('\n'));

console.log('wrote modules.js (' + reg.map(r => r.id).join(', ') + ') and dashboard-data.js (' + modules.length + ' modules) from ' + bankFile);
