#!/usr/bin/env node
'use strict';
/*
 * generate_registry.js — SINGLE SOURCE OF MODULES.
 *
 * Reads the newest canonical bank and writes two generated files:
 *   - modules.js       : window.HERO_MODULES (id, num, label, short, track, group, url, total, pass)
 *                        plus self-init wiring that fills the nav <select id="module-select">
 *                        and the dashboard filter host <div id="dash-mod-filters"> on every page.
 *   - dashboard-data.js: DASH_MODULE_REGISTRY (label, totalQ, answerKey, questions) for drill-down.
 *                        Questions carry revisedOn when the bank records that their text
 *                        changed on a date, so per-question analytics can keep attempts
 *                        from before and after a recalibration apart.
 *
 * Two tracks share the registry. The main programme numbers its modules 1..7 ("MOD 3"); the
 * Speed Training track numbers its sessions 1..4 within its own track. Reusing 1..4 for both
 * would put two entries reading "3" in front of the same participant, so Speed modules get
 * sort numbers 101.. (they sort after MOD 7) and a "SPEED n" short label, and the nav
 * <select> is grouped into <optgroup>s by track.
 *
 * Adding a module to the bank and re-running this is enough for it to appear in the nav
 * menu and the dashboard filters everywhere. verify_registry.js fails the build if these
 * generated files or the pages drift from the bank.
 *
 * Sections (shown in drill-down) are harvested from each page's QUESTIONS array, since the
 * bank does not carry a section field.
 *
 * Usage: node tools/generate_registry.js
 */
const fs = require('fs');
const path = require('path');

const REPO = path.resolve(__dirname, '..');
const LET = ['A', 'B', 'C', 'D'];

function newestBank() {
  const banks = fs.readdirSync(REPO).filter(f => /^KC_Canonical_QuestionBank_v\d+.*\.json$/.test(f));
  banks.sort((a, b) => (parseInt((a.match(/_v(\d+)/) || [])[1] || 0)) - (parseInt((b.match(/_v(\d+)/) || [])[1] || 0)));
  return banks[banks.length - 1];
}
function pageFile(id) { return id === 'mod1' ? 'quiz.js' : `${id}.js`; }

// ── Tracks ───────────────────────────────────────────────────────────────────
// A module's track comes from the bank's "track" field; modules written before the
// field existed are main-programme modules. sortBase keeps each track's block
// contiguous and in the order the tracks are listed here.
const TRACKS = {
  main:  { group: 'Main programme', sortBase: 0,   shortPrefix: 'MOD' },
  speed: { group: 'Speed Training', sortBase: 100, shortPrefix: 'SPEED' }
};
function trackOf(m) { return TRACKS[m.track] ? m.track : 'main'; }
// Position within the track: track_position when the bank states it, else the digits
// in the module_id (mod3 -> 3).
function positionOf(m) {
  if (Number.isFinite(m.track_position)) return m.track_position;
  const digits = String(m.module_id).match(/(\d+)/);
  return digits ? parseInt(digits[1], 10) : 0;
}
// Sort number. Not rendered anywhere itself, but `short` is derived from the POSITION,
// not from this, so a Speed session never renders as "MOD 101".
function sortNum(m) { return TRACKS[trackOf(m)].sortBase + positionOf(m); }
function shortOf(m) { return TRACKS[trackOf(m)].shortPrefix + ' ' + positionOf(m); }
function urlFor(quizUrl) {
  if (!quizUrl) return null;
  if (quizUrl.endsWith('/')) return 'index.html';
  return quizUrl.split('/').pop();
}
function esc(s) { return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;'); }
function jsstr(s) { return String(s).replace(/\\/g, '\\\\').replace(/'/g, "\\'"); }

// extract id->section from a page's QUESTIONS array
function extractSections(file) {
  const src = fs.readFileSync(path.join(REPO, file), 'utf8');
  const s = src.indexOf('const QUESTIONS'); const o = src.indexOf('[', s);
  let d = 0, i = o, inStr = false, sc = '', escc = false, end = -1;
  for (; i < src.length; i++) { const c = src[i];
    if (inStr) { if (escc) escc = false; else if (c === '\\') escc = true; else if (c === sc) inStr = false; continue; }
    if (c === "'" || c === '"' || c === '`') { inStr = true; sc = c; continue; }
    if (c === '[') d++; else if (c === ']') { d--; if (d === 0) { end = i; break; } } }
  const Q = eval(src.slice(o, end + 1)); // eslint-disable-line no-eval
  const map = {};
  for (const q of Q) map[q.id] = q.section || '';
  return map;
}

const bankFile = newestBank();
const bank = JSON.parse(fs.readFileSync(path.join(REPO, bankFile), 'utf8'));
const modules = bank.modules.slice().sort((a, b) => sortNum(a) - sortNum(b));

// ---- modules.js ----
const reg = modules.map(m => ({
  id: m.module_id, num: sortNum(m), label: m.nav_label || m.title, short: shortOf(m),
  track: trackOf(m), group: TRACKS[trackOf(m)].group,
  url: urlFor(m.quiz_url), total: m.total_questions, pass: m.pass_threshold
}));
const modulesJs = `// GENERATED by tools/generate_registry.js from ${bankFile} — do not edit by hand.
// Single source for the module set. Re-run the generator after changing the bank.
'use strict';
window.HERO_MODULES = [
${reg.map(r => `  { id: '${r.id}', num: ${r.num}, label: '${jsstr(r.label)}', short: '${r.short}', track: '${r.track}', group: '${jsstr(r.group)}', url: '${r.url}', total: ${r.total}, pass: ${r.pass} }`).join(',\n')}
];

(function () {
  function esc(s){return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');}
  function current(){ return (document.body && document.body.dataset) ? document.body.dataset.module : null; }
  function option(m, cur){
    return '<option value="'+m.id+'"'+(m.id===cur?' selected':'')+'>'+esc(m.label)+'</option>';
  }
  // Grouped by track, so the two programmes never read as one numbered list.
  // A single-track registry renders flat, exactly as before.
  function fillSelect(){
    var sel = document.getElementById('module-select'); if(!sel) return;
    var cur = current();
    var groups = [];
    window.HERO_MODULES.forEach(function(m){
      var name = m.group || '';
      var g = groups.filter(function(x){ return x.name === name; })[0];
      if(!g){ g = { name: name, items: [] }; groups.push(g); }
      g.items.push(m);
    });
    var body = groups.length < 2
      ? window.HERO_MODULES.map(function(m){ return option(m, cur); }).join('')
      : groups.map(function(g){
          return '<optgroup label="'+esc(g.name)+'">' +
            g.items.map(function(m){ return option(m, cur); }).join('') + '</optgroup>';
        }).join('');
    sel.innerHTML = '<option value="">— Choose a module —</option>' + body;
  }
  function fillFilters(){
    var host = document.getElementById('dash-mod-filters'); if(!host) return;
    host.innerHTML = window.HERO_MODULES.map(function(m){
      return '<label style="display:flex;align-items:center;gap:6px;font-size:13px;color:var(--gray-light);cursor:pointer;">' +
        '<input type="checkbox" class="mod-filter-check" value="'+m.id+'" checked style="accent-color:var(--teal);width:14px;height:14px;cursor:pointer;"> ' +
        esc(m.label) + '</label>';
    }).join('');
  }
  document.addEventListener('DOMContentLoaded', function(){ fillSelect(); fillFilters(); });
})();
`;
fs.writeFileSync(path.join(REPO, 'modules.js'), modulesJs);

// ---- dashboard-data.js ----
const parts = [];
parts.push("'use strict';");
parts.push('');
parts.push('// GENERATED by tools/generate_registry.js from ' + bankFile + ' — do not edit by hand.');
parts.push('// Central registry of all module question data for the dashboard drill-down.');
parts.push('const DASH_MODULE_REGISTRY = {');
modules.forEach((m, mi) => {
  const sections = fs.existsSync(path.join(REPO, pageFile(m.module_id))) ? extractSections(pageFile(m.module_id)) : {};
  const ak = m.questions.map(q => `${q.id}:'${q.correct}'`).join(', ');
  parts.push(`  ${m.module_id}: {`);
  parts.push(`    label: '${jsstr(m.nav_label || m.title)}',`);
  parts.push(`    totalQ: ${m.total_questions},`);
  parts.push(`    answerKey: { ${ak} },`);
  parts.push('    questions: [');
  m.questions.forEach(q => {
    const num = parseInt(q.id.replace('Q', ''), 10);
    const opts = LET.map(k => `${k}:'${jsstr(q.options[k])}'`).join(', ');
    const section = sections[num] || '';
    // revisedOn marks a question whose fingerprint moved on that date: attempts recorded
    // before it answered different text and must not be averaged with attempts after.
    const revised = q.revised_on ? `, revisedOn:'${jsstr(q.revised_on)}'` : '';
    parts.push(`      { id:${num}, text:'${jsstr(q.text)}', options:{ ${opts} }, slideRefs:'${jsstr(q.slide_refs || '')}', section:'${jsstr(section)}'${revised} },`);
  });
  parts.push('    ]');
  parts.push('  }' + (mi < modules.length - 1 ? ',' : ''));
});
parts.push('};');
parts.push('');
fs.writeFileSync(path.join(REPO, 'dashboard-data.js'), parts.join('\n'));

console.log('wrote modules.js (' + reg.map(r => r.id).join(', ') + ') and dashboard-data.js (' + modules.length + ' modules) from ' + bankFile);
